version: '3.8'

services:
  # Сервис для PostgreSQL
  db:
    image: postgres:13
    container_name: generation_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: generation_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Сервис для FastAPI приложения
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: fastapi_app
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/generation_db
      - RABBITMQ_URL=amqp://guest:guest@localhost/
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network
    volumes:
      - ..:/app  # Монтируем весь проект в контейнер

#  # Сервис для Notification Service (с уведомлениями)
#  notification_service:
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile.notification.yml  # Новый Dockerfile для Notification сервиса
#    container_name: notification_service
#    ports:
#      - "8002:8002"  # Порт, через который WebSocket будет доступен
#    depends_on:
#      - rabbitmq
#    networks:
#      - app-network
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local