# Используем официальный образ Python
FROM python:3.12

# Устанавливаем рабочую директорию
WORKDIR /app_noti

# Копируем все файлы из корневой директории проекта в контейнер
COPY ../ /app_noti

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r /app_noti/docker/requirements.txt

# Открываем порт для FastAPI приложения
EXPOSE 8002

# Запускаем сервер
CMD ["uvicorn", "notification_service:app", "--host", "0.0.0.0", "--port", "8002"]